#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 自动驾驶.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 分级与运行设计域定位
  9.2 法域与合规路径与时点
  9.3 证据等级与数字口径
  9.4 安全论证形态
  9.5 架构与中间表示
  9.6 评测口径与数据分布迁移
  9.7 岗位与组织落点

背后的心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。
  • 运行设计域是一切承诺的边界，越界之后的行为比越界之前更重要: 任何能力宣称在脱离 ODD 之后立刻归零，所以这一行真正的工程重心是「超出边界时系统做什么」——降级、最小风险策略、接管请求，而不是「边界内开得多好」。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "分级与运行设计域定位"
  "法域与合规路径与时点"
  "证据等级与数字口径"
  "安全论证形态"
  "架构与中间表示"
  "评测口径与数据分布迁移"
  "岗位与组织落点"
)
declare -a DIM_QUESTIONS=(
  "这个问题谈的是 L2 组合驾驶辅助、L3 有条件自动驾驶还是 L4 限定区域无人化；对应的 ODD 或 ODC 的 include、exclude 与越界响应分别是什么；分级依据的是 SAE J3016_202104 还是 GB/T 40429—2021。"
  "这件事发生在中国、美国还是欧洲；对应的准入路径是名单制试点、自认证加事后召回还是型式认证；相关标准当前处于已生效、已发布未生效、试点还是征求意见稿。"
  "手上每一条关键陈述来自哪一档证据——同行评议论文、监管强制披露、上市公司审计披露、企业技术博客、厂商发布会、媒体转述；每个数字的分子定义、分母构成、统计年份与统计方。"
  "对方走的是四条证明路径中的哪一条（形式化规则、结构化安全案例、运营里程统计、场景库覆盖），论证结构是否可寻址，有没有主动写出的已知限制与反论证。"
  "梯度传到哪一层、中间表示是什么（二维框、BEV、占据栅格、矢量地图）、安全兜底层是否独立于神经网络、闭环验证在哪里做的。"
  "引用的成绩来自开环还是闭环、背景交通用什么模型、路线长度与场景分布、数据集的地理与季节覆盖，以及这些条件与提问者实际运行环境的差距。"
  "这件事落在哪几张工作流卡片上、由哪个岗位负责、以及它会不会触发功能安全与合规侧的否决权；跨境项目还要看是否涉及测绘资质、数据出境、OTA 备案这三段中国独有的环节。"
)
declare -a DIM_SOURCES=(
  "\`references/research/06-glossary.md\` 第 1 节与第 8 节的中英口径差异表；SAE J3016 条目页与国家标准全文公开系统的 GB/T 40429—2021 原文。"
  "工业和信息化部装备工业一司与国家标准全文公开系统；NHTSA 与加州 DMV 与 CPUC；UNECE WP.29 与 GRVA 文件库。对应清单见 \`references/research/05-sources.md\` A、B、C 三组。"
  "SEC EDGAR 与港交所披露；Waymo 的同行评议安全研究页；NHTSA 强制事故报告数据集与加州 DMV 脱离报告；企业官方技术博客。厂商发布会与演示视频一律降级为「宣称」。"
  "\`references/research/04-canon.md\` 第三节的标准原文条目；UL 4600 与 ISO 21448 与 ISO 34502 条目页；Koopman 的公开讲义与长文；企业公开的 Safety Case 材料。"
  "\`references/research/02-tools.md\` 第 1 至 3 节与第 7 节；UniAD、BEVFormer、MapTR、TransFuser 的官方仓库与论文。"
  "nuScenes、nuPlan、Bench2Drive、NAVSIM、CARLA Leaderboard、Waymo Open Dataset 的官方页与 devkit；carla_garage 的闭环评测方法论纠偏材料。"
  "\`references/research/03-workflows.md\` 的岗位差异表与中国欧美流程差异表。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句「本问题落在 L{N} / ODD 为 {范围} / exclude 项为 {列表} / 越界响应为 {MRC 描述}」，外加一句该分级在提问者所在法域的对应名称。"
  "一张「法域 / 适用文件编号与版本 / 发布日期 / 实施日期 / 当前状态 / 对本问题的约束」的小表，未生效的条目必须显式标注。"
  "给每条关键陈述打一个证据等级标签，并对每个引用的数字补一句口径说明；口径填不满的数字不进结论。"
  "一句「所走路径 + 该路径的公开弱点 + 本案例是否补齐了该弱点」，以及一句缺失证据清单。"
  "一句架构判断加一句「这个中间表示能不能表达『不认识但那里有东西』」，并指出兜底层的独立性状况。"
  "一句「该成绩的成立条件」加一句「迁移到提问者场景时最可能失效的地方」，中文受众默认加一句欧美基准不外推中国路况的提醒。"
  "一句「主责岗位 + 涉及的工作流编号 + 是否需要合规前置」，跨境场景补一句最容易漏排期的环节。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
