#!/usr/bin/env bash
# safety-case.sh — 安全案例（safety case）的持续维护 (Decay risk: medium) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="安全案例（safety case）的持续维护 (Decay risk: medium)"

usage() {
  cat <<EOF
safety-case.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./safety-case.sh             # interactive
  ./safety-case.sh --dry-run
  ./safety-case.sh --json
  ./safety-case.sh --explain
  ./safety-case.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "安全案例（safety case）的持续维护 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**安全负责人**写顶层主张。典型写法是「我们的自动驾驶车辆在公共道路上运行是可接受地安全的」这一类可被质疑、可被证据支撑的陈述。产出：顶层主张【行业惯例：UL 4600 是目标导向、技术中立的安全案例评估标准，要求你把论证讲完整并给出证据，但它是自愿性标准，不是法规】(evidence: [T03-S005], [T03-S019])"
  "**拆子主张**：按能力域（感知/决策/失效响应/网络安全/运营）或按论证维度拆。公开的做法（Aurora）是把顶层主张分解成多层子主张，最终由**数百条安全主张与数千份证据**支撑；其框架用 GSN（目标结构化表示法）公开发布【单家做法，已公开可查】(evidence: [T03-S019], [T03-S020])"
  "**给每条子主张挂证据**：证据来自前面所有卡片——ODD 规格、HARA、SOTIF 报告、场景库覆盖度、仿真/场地/道路测试结果、现场运营数据。产出：主张—证据映射表。判据：每条主张至少一条可验证证据，且证据带版本"
  "**定安全性能指标（SPI）**：UL 4600 第 3 版（**2023-03-17 发布**）对 safety performance indicator 给出更精确的定义，并新增**事故后行为（post-incident behavior）**要求【明文要求：标准条款，但标准本身自愿】(evidence: [T03-S005])"
  "**建评审与治理机制**：谁有权判定「证据足够」。Waymo 公开的做法是用**十二条验收判据**评估 ADS 是否可以部署，并设有安全框架指导委员会与安全委员会等多层治理；其就绪判定是针对**特定 ADS 配置 + 特定 ODD + 特定用例 + 特定车辆平台**做的离散判定，且是持续评估而非一次性【单家做法，已公开】(evidence: [T03-S029], [T03-S030])"
  "**变更触发更新**：每次 ODD 变更、架构变更、重大事故、新城市/新平台上线，都要回来更新对应子主张与证据 (evidence: [T03-S030])"
  "**第三方审视**（可选但越来越常见）：外部评估机构对安全案例的结构与证据做评估。**注意：拿到 UL 4600 评估 ≠ 取得上路许可**，两者不是一回事 (evidence: [T03-S005])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "safety-case-walkthrough"
fi
