#!/usr/bin/env bash
# workflow-14.sh — 示范运营与远程协助值守 (Decay risk: medium) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="示范运营与远程协助值守 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-14.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-14.sh             # interactive
  ./workflow-14.sh --dry-run
  ./workflow-14.sh --json
  ./workflow-14.sh --explain
  ./workflow-14.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "示范运营与远程协助值守 (Decay risk: medium)" 工作流。

入门 SOP 共 8 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**合规负责人**确认许可档位。中国：道路测试 → 示范应用 → 安全评估 → 道路应用试点（北京口径）；「示范应用」与「商业化运营」是两个不同档位，「开放载人」不等于「可以收费」【明文要求，地域限定】(evidence: [T03-S037], [T03-S038])。美国加州：DMV 的测试/部署许可管「车能不能上路」，CPUC 的许可管「能不能载客、能不能收费」，两套许可分属两个机构【明文要求】(evidence: [T03-S064], [T03-S010])"
  "**划运营域**：把 ODD（卡片 1）落到具体的路网、时段、天气门限、上下客点。产出：运营域地图与准入/退出规则"
  "**建远程值守台**：**先把概念分清楚**——\`remote assistance\`（远程协助）是远程人员**不接管控制**，只在 ADS 遇到自己无法处置的情境时提供信息与建议以便继续行程，ADS 全程执行动态驾驶任务，对人的响应没有实时性要求，且只在 L4/L5 存在；\`remote driving\`（远程驾驶）是车外的人实时执行驾驶任务，**J3016 明确其不属于驾驶自动化**。这两个词在合规文书里选错，等于改变了「谁在开车」和事故责任归属【明文要求：术语标准与分类学】(evidence: [T03-S031])"
  "**定值守流程**：请求触发条件、坐席接单、处置手段清单（给建议/给路径提示/授权通过）、升级路径、超时兜底。产出：值守 SOP。判据：每种处置手段都能对应「车辆是否让渡了控制权」这一问题的明确答案"
  "**人员与配比**：中国部分地方的示范运营实施细则对远程人员配比有具体要求（如远程驾驶按 1:1 配置的说法在行业报道中常见）——**本轨未从地方实施细则原文核实具体比例数字，不予采信为明文要求**；能核实的是北京条例明文要求道路应用试点须配备安全员、平台安全监控人员并掌握遵守道交法规【明文要求】(evidence: [T03-S037])"
  "**接入 SOTIF 分析**：ISO 21448:2022 明确把**远程用户对车辆的操作或协助、以及能影响车辆决策的后台通信纳入范围**——远程台不是运营部门的私事，是安全分析对象【明文要求】(evidence: [T03-S001])"
  "**日常运营指标**：接管/协助请求率、坐席响应时延、每次协助时长、协助后事件率。产出：运营看板"
  "**事件响应联动**：远程台是事故第一现场的信息节点，与卡片 12 的证据保全和上报流程打通"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-14-walkthrough"
fi
