#!/usr/bin/env bash
# workflow-9.sh — 实车路测与影子模式验证 (Decay risk: medium) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="实车路测与影子模式验证 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-9.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-9.sh             # interactive
  ./workflow-9.sh --dry-run
  ./workflow-9.sh --json
  ./workflow-9.sh --explain
  ./workflow-9.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "实车路测与影子模式验证 (Decay risk: medium)" 工作流。

入门 SOP 共 8 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**合规工程师**先拿路测资格。中国由**地方**发放智能网联汽车道路测试通知书，跨城不通用；北京的路径是道路测试 → 示范应用 → 安全评估 → 道路应用试点四步走【明文要求，地域限定】(evidence: [T03-S037], [T03-S038])。美国由各州发放，加州 DMV 分为带驾驶员测试、无驾驶员测试、部署三类许可【明文要求】(evidence: [T03-S064])"
  "**安全员培训与考核**：安全员/平台安全监控人员需掌握并遵守道路交通安全法律法规，事故时应采取必要安全处置措施并迅速报告公安交管部门。产出：培训记录与上岗资格【明文要求：北京条例】(evidence: [T03-S037])"
  "定**测试计划**：路线、里程目标、场景清单、天气与时段分布，与 ODD 对齐。产出：测试计划。判据：里程分布能对上 ODD 声明的运行条件，而不是「哪条路好开跑哪条」"
  "**数据记录**：全量或触发式记录，保证每次接管前后有足够上下文。产出：数据规范。判据：每次接管都能复现"
  "**接管/脱离的现场记录**：安全员在车上立即打标签（原因初判 + 主观严重度）。产出：接管日志。跳过的后果：事后回看视频猜原因，归因准确率大幅下降"
  "**每日/每周脱离复盘会**：把接管按原因分类。美国 DOT 相关梳理里用到的分类维度包括控制偏差、环境与其他道路使用者、软硬件异常、感知偏差、规划偏差、操作员主动接管等【行业惯例/官方梳理，不是强制分类法】(evidence: [T03-S072])"
  "**影子模式**：在量产车上让新算法只推理不控车，把它的输出与人类驾驶或现网算法比对，分歧点回传。产出：分歧样本流。这一支是数据闭环最主要的低成本来源之一【行业惯例，具体触发器设计各家不同】(evidence: [T03-S021])"
  "**年度报送**（加州）：持加州测试许可的主体须按 DMV 要求提交年度脱离报告【明文要求，仅加州】(evidence: [T03-S009])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-9-walkthrough"
fi
