#!/usr/bin/env bash
# workflow-8.sh — 闭环仿真与场景回归（场景库构建、参数化、覆盖度） (Decay risk: medium) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="闭环仿真与场景回归（场景库构建、参数化、覆盖度） (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-8.sh             # interactive
  ./workflow-8.sh --dry-run
  ./workflow-8.sh --json
  ./workflow-8.sh --explain
  ./workflow-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "闭环仿真与场景回归（场景库构建、参数化、覆盖度） (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**仿真工程师**定场景抽象层级：功能场景（自然语言）→ 抽象/逻辑场景（带参数范围）→ 具体场景（参数取定值）。产出：场景分层规范。判据：每个场景都能说清自己在哪一层 (evidence: [T03-S061])"
  "选**描述格式**：路网用 ASAM OpenDRIVE，动态场景用 ASAM OpenSCENARIO，仿真软件接口用 ASAM 的 OpenX 族。产出：格式与工具链选型【行业惯例：ASAM 是行业协会标准，非法规强制】(evidence: [T03-S028])"
  "建**场景来源的四条渠道**：法规/标准场景、自然驾驶数据提取、专家设计的危险场景、参数泛化生成。产出：场景库 v1 与来源标签。判据：每个场景能追溯到来源，法规类场景与自研场景分区管理 (evidence: [T03-S053], [T03-S054])"
  "**参数化与泛化**：对逻辑场景的参数范围做采样（网格/随机/重要性采样/搜索），批量生成具体场景。产出：测试用例集 (evidence: [T03-S053])"
  "定**覆盖度口径**（最容易糊弄的一步）：覆盖度必须写清分母——是 ODD 属性组合的覆盖、还是逻辑场景参数空间的覆盖、还是法规场景清单的覆盖。产出：覆盖度定义文档。判据：任何一个覆盖度数字都能回答「分母是什么」"
  "**建回归门禁**：每次提交/每晚跑一批场景，结果与基线对比；关键指标退化即阻断。产出：CI 报告与阻断规则 (evidence: [T03-S055], [T03-S051])"
  "**问题闭环**：仿真发现的问题 → 归因分类 → 修复 → 复现验证 → 场景入库。产出：问题闭环台账（这一步正是仿真测试岗位 JD 里反复出现的日常职责链条）(evidence: [T03-S051])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-8-walkthrough"
fi
