#!/usr/bin/env bash
# workflow-2.sh — 危害分析与风险评估到安全目标与 ASIL 分解 (Decay risk: low) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="危害分析与风险评估到安全目标与 ASIL 分解 (Decay risk: low)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "危害分析与风险评估到安全目标与 ASIL 分解 (Decay risk: low)" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**功能安全工程师**冻结 item definition（与卡片 1 的产出同源）。判据：功能边界、接口、运行环境都已写死；HARA 不能建在活动的靶子上【明文要求】(evidence: [T03-S004])"
  "枚举**运行场景 × 故障行为**矩阵：把 ODD 拆成运行情境（高速直行、匝道、拥堵跟车…），对每个情境列系统可能的失效行为（无输出、错误输出、时序错误…）。产出：危害事件清单。判据：每条都是「在某情境下、系统某种失效行为、导致某种可能伤害」的完整三元组"
  "对每个危害事件打 **S（严重度）× E（暴露率）× C（可控性）**，查表得 ASIL（QM / A / B / C / D）。产出：HARA 表。判据：每个 S/E/C 打分都有书面理由，不能只有数字【明文要求】(evidence: [T03-S004])"
  "每个非 QM 的危害事件至少推出一条**安全目标**，并给出安全状态与 **FTTI（故障容错时间间隔）**。产出：安全目标清单。判据：安全目标是「避免什么」的表述，不是「实现什么」"
  "做**功能安全概念**：把安全目标分配到架构元素，必要时做 **ASIL 分解**（把一个高 ASIL 需求拆到两个充分独立的元素上，各降一档）。产出：功能安全概念 + 分解论证。判据：分解的前提是**充分独立性**，独立性没论证的分解无效【明文要求】(evidence: [T03-S004])"
  "**独立评审 + 配置基线**。产出：签署的 HARA 与功能安全概念"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
