#!/usr/bin/env bash
# workflow-7.sh — 预测与规划模块开发（含规则兜底层设计） (Decay risk: high) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="预测与规划模块开发（含规则兜底层设计） (Decay risk: high)"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "预测与规划模块开发（含规则兜底层设计） (Decay risk: high)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**规控工程师**定行为规格：这个功能允许做什么机动（变道、绕行、无保护左转…）、绝对不做什么、礼让策略。产出：行为规格文档。判据：每条行为都能对应一个可测的成功/失败判据"
  "建**分层架构**：行为决策 / 轨迹规划 / 跟踪控制的职责边界写死，接口冻结。产出：架构文档。这一步不做的后果：后期出问题时无法定位是哪一层的责任"
  "预测模块：给周围交通参与者出多模态轨迹与概率。产出：预测模型 + 开环指标。**注意**：预测与规划的一体化（联合建模）是当前活跃研究方向，但一体化会让「预测错了还是规划错了」变难归因，这是量产团队的实际权衡 (evidence: [T03-S073])"
  "**设计兜底层**（本卡片最关键的一步）：在学习型规划器之外加一层规则化检查——碰撞检查、物理可行性、运动学约束、安全距离模型。公开发表的做法（Lyft L5 的 SafetyNet）是让规则化 fallback 层对 ML 规划器的输出做 sanity check，不通过就切到规则轨迹【单家做法，已同行公开】(evidence: [T03-S066])"
  "定义**降级阶梯**：性能层（学习型）→ 兜底层（规则型）→ 失效安全层（最小风险操作）。每一级的触发条件与退出条件写清。产出：降级状态机。判据：能对上卡片 1 的 MRC 定义与卡片 2 的安全目标"
  "**闭环评测**：在仿真里跑闭环（不是拿真值喂给规划器的开环），看碰撞率、违规率、舒适度、进度。产出：闭环指标表 (evidence: [T03-S048], [T03-S049])"
  "**实车标定与主观评价**：老司机 + 普通用户双盲试乘打分，与客观指标一起看。产出：主观评价报告"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
