#!/usr/bin/env bash
# workflow-13.sh — 量产准入与型式认证材料准备 (Decay risk: high) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="量产准入与型式认证材料准备 (Decay risk: high)"

usage() {
  cat <<EOF
workflow-13.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-13.sh             # interactive
  ./workflow-13.sh --dry-run
  ./workflow-13.sh --json
  ./workflow-13.sh --explain
  ./workflow-13.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "量产准入与型式认证材料准备 (Decay risk: high)" 工作流。

入门 SOP 共 8 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**合规工程师**先确定走哪条通道。三套制度完全不同：中国 = 公告 + CCC，智能网联另有准入试点通道；欧盟/UNECE = 型式认证（上市前逐项测试并签发证书）；美国 = FMVSS 自认证 + 事后召回，不符合某条 FMVSS 的车走豁免程序。产出：通道判定书。判据：这三个体系里「认证」二字含义不同，混用必错"
  "**中国 L2 路线**：对齐 GB 47955—2026《智能网联汽车 组合驾驶辅助系统安全要求》。编号无「/T」= **强制性**国标；**2026-06-27 批准发布，官方表述为拟 2027-01-01 起正式实施**，截至 2026-09-06 状态是 **\`已发布未生效\`**。适用三类产品：基础单车道行驶控制、基础多车道行驶控制、领航驾驶辅助（NOA）。内容支柱为产品能力表现 + 安全保障要求 + 使用方式规范，验证方式是场地试验 + 道路试验 + 文件检验的多层级体系【明文要求，生效日未到】(evidence: [T03-S012])"
  "**中国 L3/L4 路线**：走四部门《关于开展智能网联汽车准入和上路通行试点工作的通知》（工信部联通装〔2023〕217 号，2023-11 发布，\`试点/试行\`）。对象是**具备量产条件的 3 级和 4 级**产品。由**汽车生产企业和使用主体组成联合体**，参考试点实施指南制定申报方案，经车辆拟运行城市人民政府同意并盖章后，向所在地省级工业和信息化主管部门**自愿申报**。试点组织实施分**五个阶段**：试点申报、产品准入试点、上路通行试点、试点暂停与退出、评估调整【明文要求】(evidence: [T03-S016], [T03-S017])"
  "**准备测试验证证据**：官方解读明确，具备自动驾驶功能的产品应符合**模拟仿真、封闭场地、实际道路**等测试验证要求，其中实际道路测试是安全测试验证的重要支柱之一；工信部委托技术服务机构对产品准入测试与安全评估开展跟踪和技术评估，并引入安全监测和报告机制【明文要求】(evidence: [T03-S017])"
  "**信息安全与软件升级体系**：GB 44495/44496/44497—2024（2024-08-23 发布、2026-01-01 实施，\`已生效\`）。GB 44495 参考吸收 ISO/SAE 21434 与 UNECE R155 的框架【明文要求】(evidence: [T03-S042])"
  "**欧盟/UNECE 路线**：L3 高速对齐 UN R157（ALKS）。**注意四个限定语**：01 系列修订把上限提到 130 km/h、但只有具备**变道能力**的 ALKS 才被允许在 60 km/h 以上运行、适用乘用车与轻型商用车与高速公路类道路、且**只在选择适用该修订的缔约方**生效【明文要求，缔约方限定】(evidence: [T03-S011])。另需 R155/R156 的 CSMS/SUMS 企业体系证书作为前置"
  "**美国路线**：FMVSS 自认证；对不符合某条 FMVSS 的车辆（如无方向盘无踏板）走 49 CFR Part 555 豁免，**豁免有数量上限与期限**，不是永久放行。各州另发测试与部署许可，加州 DMV 分带驾驶员测试、无驾驶员测试、部署三类，载客收费另需 CPUC 许可【明文要求】(evidence: [T03-S045], [T03-S064], [T03-S010])"
  "**材料集成与内审**：把 ODD 规格、HARA、SOTIF 报告、场景库覆盖度、仿真与场地与道路测试报告、信息安全与 OTA 体系文件、安全案例打包，做一次以「审核员视角」的内审。产出：申报包"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-13-walkthrough"
fi
