#!/usr/bin/env bash
# workflow-12.sh — 事故与接管的复盘调查（含向监管报送） (Decay risk: high) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="事故与接管的复盘调查（含向监管报送） (Decay risk: high)"

usage() {
  cat <<EOF
workflow-12.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-12.sh             # interactive
  ./workflow-12.sh --dry-run
  ./workflow-12.sh --json
  ./workflow-12.sh --explain
  ./workflow-12.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "事故与接管的复盘调查（含向监管报送） (Decay risk: high)" 工作流。

入门 SOP 共 8 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**现场处置**：安全员/远程值守人员按预案处置并**迅速报告公安交管部门**（中国）；配合事故调查处理并按要求提供证据材料，企业还须按要求提供事故过程信息或事故分析报告【明文要求：北京条例】(evidence: [T03-S037], [T03-S038])"
  "**证据保全**：锁定该车该时段的全量数据（传感器、决策日志、车辆状态、DSSAD 记录）。产出：证据包与哈希。判据：链路可追溯、不可事后修改。GB 44497—2024《智能网联汽车 自动驾驶数据记录系统》自 2026-01-01 实施，把记录能力变成强制项【明文要求】(evidence: [T03-S042])"
  "**法定上报（美国）**：装备 ADS（L3–L5）或 SAE L2 ADAS 的制造商与运营方，在碰撞前 30 秒内自动化处于激活状态且满足特定后果（送医、致死、气囊起爆、涉及弱势道路使用者、需拖离等）时须向 NHTSA 报告。第三次修订令 **2025-04-24 签发、2025-06-16 生效**，把致死/送医/撞击弱势道路使用者类的首报时限从 **1 天放宽到 5 个日历日**，并取消同一起事故多主体重复上报【明文要求】(evidence: [T03-S007], [T03-S008])"
  "**法定上报（中国）**：试点主体按试点实施指南建立事故报告机制；地方条例（如北京）另有报告与配合调查义务。**中国没有全国统一公开的 AV 事故数据库**，与美国 SGO 的数据可得性差异巨大，中美事故数据不可直接横向比较【明文要求 + 口径提醒】(evidence: [T03-S016], [T03-S037])"
  "**时间线重建**：把感知输出、预测、决策、控制指令、车辆响应对齐到同一时间轴。产出：秒级（必要时毫秒级）时间线"
  "**根因分析**：区分是失效（ISO 26262 域）还是功能不足（ISO 21448 域）——**这个分类决定后面整改走哪条流程**，分错会让整改永远无法闭环 (evidence: [T03-S001], [T03-S004])"
  "**系统性整改**：不只修这一例，要问「同族问题还有多少」（接卡片 10）与「我们的安全案例哪条论证被证伪了」（接卡片 15）"
  "**对外沟通与召回判定**：在美国，若构成不合理安全风险则走召回程序并向 NHTSA 提交；NHTSA 召回数据库是 AV 监管动作的主要留痕地【明文要求】(evidence: [T03-S071])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-12-walkthrough"
fi
