#!/usr/bin/env bash
# workflow-4.sh — 数据采集与合规处理（中国：测绘资质 / 数据出境 / 脱敏） (Decay risk: high) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="数据采集与合规处理（中国：测绘资质 / 数据出境 / 脱敏） (Decay risk: high)"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "数据采集与合规处理（中国：测绘资质 / 数据出境 / 脱敏） (Decay risk: high)" 工作流。

入门 SOP 共 8 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**合规工程师 + 法务**先做**性质判定**：车端采集并回传的坐标、影像、点云及道路设施属性信息，在中国被认定为**测绘活动**；相关采集、存储、传输、处理与地图制作，应由具备**导航电子地图制作测绘资质**的单位承担【明文要求】。产出：测绘合规路径判定书 (evidence: [T03-S014])"
  "选**资质路径**：自建甲级资质 / 与有资质单位签约由其承担相应环节 / 通过投资合作间接取得。产出：资质方案与合作协议。判据：链路上每一个「采、存、传、处、制」环节都能指到一个有资质的主体。**注意这是主体资质，不是产品认证**——这是外行最容易混的一处 (evidence: [T03-S014])"
  "**数据合规**：按《汽车数据安全管理若干规定（试行）》（五部门，2021-10-01 起施行，\`已生效（试行）\`）建立处理规则。**准确口径**：车内处理、默认不收集、精度范围适用、脱敏处理这四条原则，条文写的是国家**鼓励、倡导**汽车数据处理者坚持，属倡导性表述，**不是「一律禁止向车外传数据」**【明文要求：文本为倡导性】(evidence: [T03-S015])"
  "做**重要数据识别**：《汽车数据出境安全指引（2026版）》（八部门，2026-02-03 印发）面向研发设计、生产制造、驾驶自动化、软件升级、联网运行等典型业务场景细化了汽车重要数据的判定规则。产出：重要数据清单与判定依据【明文要求】(evidence: [T03-S033], [T03-S034])"
  "**境内存储**：重要数据应当依法在境内存储。产出：数据存储与访问控制架构图【明文要求】(evidence: [T03-S015])"
  "**出境路径选择**（只在确需出境时）：三条管理方式——申报**数据出境安全评估** / 订立**个人信息出境标准合同** / 通过**个人信息出境认证**；2026 版指引明确了三者的适用条件，并列出**九类免于上述三种管理方式的情形**。产出：出境方案与申报材料【明文要求】(evidence: [T03-S033], [T03-S034])"
  "**脱敏与技术防护**：人脸、车牌等的匿名化/去标识化处理节点尽量前移到车端或境内边缘；2026 版指引从管理制度、技术防护、日志管理、应急处置四方面提出保护要求。产出：脱敏方案 + 日志留存方案【明文要求】(evidence: [T03-S033], [T03-S034])"
  "**年度动作**：按《汽车数据安全管理若干规定（试行）》做风险评估报告与年度报告报送，配合抽查核验【明文要求】(evidence: [T03-S015])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
