#!/usr/bin/env bash
# workflow-1.sh — 功能定义与运行设计域（ODD）划定 (Decay risk: medium) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="功能定义与运行设计域（ODD）划定 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "功能定义与运行设计域（ODD）划定 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**产品经理 + 系统工程师**写 item definition（项目定义）：功能做什么、不做什么、与哪些系统有接口、驾驶员/乘员承担什么角色。产出：一份 item definition 文档。判据：外人读完能复述「这个功能不负责什么」。这是 ISO 26262 概念阶段的起点【明文要求】(evidence: [T03-S004])"
  "**系统工程师**按 ISO 34503:2023 的分层分类学列 ODD 属性：scenery（道路几何、路面、固定设施）/ environmental（天气、光照、连通性）/ dynamic elements（其他交通参与者及其行为）三大类逐项填。产出：ODD 属性表。判据：每个属性都有 include / exclude / conditional 三种表述之一，不留「未定义」【明文要求】(evidence: [T03-S002], [T03-S063])"
  "用 ISO 34503 的四类语句写死边界：mode / include / exclude / conditional。**exclude 项必须和 include 项一样详细**——这是入门最容易偷懒的地方。产出：机器可读的 ODD 规格。判据：能被场景生成工具直接消费 (evidence: [T03-S002], [T03-S056])"
  "**系统工程师 + 感知负责人**给每个 ODD 属性挂一个**可在线检测的信号**（雨量、能见度估计、地图置信度、定位协方差…）。产出：ODD 监控信号表。判据：每条边界都答得出「车端怎么知道自己出界了」。跳过这步的后果很具体：ODD 写在 PPT 上而车端无法自检，退出机制无从触发"
  "定义**退出策略与最小风险状态（MRC）**：出 ODD 时给驾驶员多长的接管请求时间、无人接管时怎么停、停在哪。产出：MRC 与降级矩阵。判据：对 L3 要能对上 UN R157 的过渡需求与最小风险操作要求【明文要求，适用于走 UNECE 型式认证的产品】(evidence: [T03-S011])"
  "**合规工程师**做法规映射：目标市场分别落到哪套文件上——中国 L2 落 GB 47955—2026（2026-06-27 发布、拟 2027-01-01 实施，\`已发布未生效\`）；中国 L3/L4 落四部门准入试点通道（\`试点/试行\`）；欧盟 L3 高速落 UN R157（\`已生效\`，对适用缔约方）；美国走 FMVSS 自认证 + 州级许可。产出：法规适用矩阵 (evidence: [T03-S012], [T03-S016], [T03-S011])"
  "**评审**：产品、系统、功能安全、法务四方会签。产出：ODD 基线 v1.0，进配置管理。判据：任何后续 ODD 变更都要走变更单"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
