#!/usr/bin/env bash
# workflow-11.sh — 版本发布与整车 OTA（中国备案与准入许可的分流） (Decay risk: high) SOP walkthrough for 自动驾驶.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
WORKFLOW="版本发布与整车 OTA（中国备案与准入许可的分流） (Decay risk: high)"

usage() {
  cat <<EOF
workflow-11.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-11.sh             # interactive
  ./workflow-11.sh --dry-run
  ./workflow-11.sh --json
  ./workflow-11.sh --explain
  ./workflow-11.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "版本发布与整车 OTA（中国备案与准入许可的分流） (Decay risk: high)" 工作流。

入门 SOP 共 9 步, 失败模式自检 0 项。

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**发布经理**冻结版本并跑完整回归（卡片 8）+ 关键实车验证（卡片 9）。产出：发布候选版本与测试报告"
  "**判定升级性质**（中国团队的第一个分叉）：本次升级是否涉及安全、环保、节能、防盗技术性能参数变更；是否涉及自动驾驶功能。产出：升级性质判定单【明文要求】(evidence: [T03-S040], [T03-S041])"
  "**走对应备案通道**：按 2022 年《关于开展汽车软件在线升级备案的通知》，企业需依次完成**企业管理能力备案 → 车型与功能备案 → 具体升级活动备案**；不涉及上述技术性能参数变更的，完成备案后可实施；涉及变更的，需先申请公告产品变更/扩展并完成公告产品准备再升级；**涉及自动驾驶功能的升级须经工业和信息化部批准**【明文要求】(evidence: [T03-S040], [T03-S041])"
  "**对齐 2025 年的收紧口径**：工信部联通装〔2025〕45 号（2025-02-25 发布，\`已生效\`）把 OTA 备案分为**简易备案类**（不涉及产品主要技术参数变更，完成备案即可升级）与**许可备案类**（涉及主要技术参数变更，须先取得产品变更许可并完成备案才能升级）；涉及自动驾驶功能的 OTA 须按准入规定取得许可【明文要求】(evidence: [T03-S013])"
  "**满足软件升级的强制国标**：GB 44496—2024《汽车软件升级通用技术要求》与 GB 44495—2024《汽车整车信息安全技术要求》**2024-08-23 发布、2026-01-01 实施**，截至 2026-09-06 为 \`已生效\`。新申请型式批准的车型自实施之日起执行，已获型式批准车型有过渡期——**过渡期长度本轨未用一手标准文本核实，引用前须查标准正文**【明文要求，过渡期细节未核】(evidence: [T03-S042])"
  "**灰度与回滚**：分批推送、监控关键指标、保留一键回滚路径。产出：灰度计划与回滚预案【行业惯例，非明文要求的具体比例】"
  "**用户告知**：升级内容、影响的功能边界、需要用户重新学习的操作。GB 47955—2026 把使用说明与用户培训列为要求支柱之一，但该标准 \`已发布未生效\`（拟 2027-01-01 实施）【明文要求，生效日未到】(evidence: [T03-S012])"
  "**升级后报送**：2022 年备案通知的官方解读明确，升级完成后企业须在 **5 个工作日内**报送实施情况【明文要求】(evidence: [T03-S041])"
  "**存量补报**（一次性）：已获准入的智能网联汽车产品，企业应在 **2025-06-01 前**向工信部与市场监管总局补充报送技术参数及验证材料——这个节点已过，新进入者应确认自己的历史产品是否已补报【明文要求】(evidence: [T03-S013])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-11-walkthrough"
fi
