#!/usr/bin/env bash
# topic-1.sh — 安全 决策助手 for 自动驾驶.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
TOPIC="安全"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 安全 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 要给一个失效现象归因 → 则 第一步不是找原因，而是选标准域：部件坏了走 ISO 26262 功能安全，没坏但不够用走 ISO 21448 预期功能安
  • 如果 一个约束需要长期维护 → 则 要写成机器可以消费的形式，不能只存在于文档里。案例：ODD 边界要落成车端可监控的信号，场景要落成 ASAM OpenS
  • 如果 在做技术尽调 → 则 问三句话就能筛掉大部分包装：对方说「支持 OpenSCENARIO」要追问是 XML 还是 DSL、哪个版本；对方的安全

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "要给一个失效现象归因"
  "一个约束需要长期维护"
  "在做技术尽调"
)
declare -a RULE_ACTIONS=(
  "第一步不是找原因，而是选标准域：部件坏了走 ISO 26262 功能安全，没坏但不够用走 ISO 21448 预期功能安全。域选错了整条整改闭环路径都是错的。案例：雨夜漏检一个横穿行人，如果是摄像头模组供电异常，走功能安全的失效分析与冗余设计；如果硬件全好、只是模型在该光照与姿态下识别不出来，走预期功能安全的场景收敛与数据补充——两条路的整改产出物、验收判据与归档位置都不同，这也是算法团队与功能安全团队最常年扯皮的一处"
  "要写成机器可以消费的形式，不能只存在于文档里。案例：ODD 边界要落成车端可监控的信号，场景要落成 ASAM OpenSCENARIO 描述，安全论证要落成 GSN 结构，技术参数要落成对照表"
  "问三句话就能筛掉大部分包装：对方说「支持 OpenSCENARIO」要追问是 XML 还是 DSL、哪个版本；对方的安全案例是不是按 GSN 组织；对方报的基准是开环还是闭环、背景交通是什么"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
