#!/usr/bin/env bash
# topic-2.sh — 案例 决策助手 for 自动驾驶.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="自动驾驶"
TOPIC="案例"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 5 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 案例 主题下的 playbook 规则组合成交互树。

基于 5 条规则:
  • 如果 看到「某方案在某榜单第一」 → 则 先查是开环还是闭环、他车行为模型是什么、路线长度与场景分布，再看名次。案例：开环榜第一在闭环里表现很差（PDM, CoR
  • 如果 要引用一条中国标准或法规 → 则 必须同时写出编号、版本、发布日期、实施日期与当前状态。案例：GB 47955—2026 组合驾驶辅助强制性国标 2026
  • 如果 一份工程交付物最终要进申报材料 → 则 格式按最终申报件反推设计，不要事后重写。案例：仿真场景回归报告直接服务量产准入，路测与影子模式的日志直接服务事故复盘与报
  • 如果 一条强制标准已发布但尚未生效 → 则 按已生效来做设计、按未生效来做表述。案例：GB 47955—2026 拟 2027-01-01 实施，产品定义与人机交互
  • 如果 在为中国量产项目选算力平台 → 则 在立项时就按目标平台反推模型结构，不要先训模型再找芯片。案例：三条链路（NVIDIA DRIVE / 地平线征程 6 加

相关心智模型:
  • 先问分母：这一行的数字默认不可比: 看到任何自动驾驶的比例、里程、事故率、脱离率，先问三件事——分母是什么、口径谁定的、哪一年；分母说不清的数字不进论证链。
  • 安全是论证出来的，不是跑出来的: 「我们跑了 N 万公里没出事」不是安全证据，只是安全论证里的一条证据；这一行目前有四套互不覆盖的证明路径，工程上叠加使用，理论上没有统一。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "看到「某方案在某榜单第一」"
  "要引用一条中国标准或法规"
  "一份工程交付物最终要进申报材料"
  "一条强制标准已发布但尚未生效"
  "在为中国量产项目选算力平台"
)
declare -a RULE_ACTIONS=(
  "先查是开环还是闭环、他车行为模型是什么、路线长度与场景分布，再看名次。案例：开环榜第一在闭环里表现很差（PDM, CoRL 2023）；nuScenes 上的开环端到端可能主要靠自车状态刷分"
  "必须同时写出编号、版本、发布日期、实施日期与当前状态。案例：GB 47955—2026 组合驾驶辅助强制性国标 2026-06-27 发布、拟 2027-01-01 实施，截至本文件采集日 2026-09-06 属「已发布未生效」——读到本条时先看今天的日期：若已过 2027-01-01，本条的状态判断已过期，须回工信部页面重新确认；GB 44495/44496/44497—2024 三项强标 2024-08-23 发布、2026-01-01 实施，属「已生效」。把未生效写成既成事实是这一行最常见的合规错误"
  "格式按最终申报件反推设计，不要事后重写。案例：仿真场景回归报告直接服务量产准入，路测与影子模式的日志直接服务事故复盘与报送，长尾闭环台账直接服务安全案例维护"
  "按已生效来做设计、按未生效来做表述。案例：GB 47955—2026 拟 2027-01-01 实施，产品定义与人机交互现在就要按它设计，但在实施日之前对外不能说「已强制要求」——这个「之前」以你读到本条的当天为准，不是以本文件的采集日为准"
  "在立项时就按目标平台反推模型结构，不要先训模型再找芯片。案例：三条链路（NVIDIA DRIVE / 地平线征程 6 加天工开物 / 高通 Snapdragon Ride Flex）的量化算子集合不同，一个在训练侧随手用了目标编译器不支持的算子的模型，到部署期要么重训要么塞进不划算的回退实现；同一案例的第二半是不要用峰值算力数字横向比较平台，厂商给的是峰值且精度口径不同，FP4 与 INT8 不可互换，实际帧率取决于模型结构、算子支持与内存带宽"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
